version: "2"

services:

  postgresdb:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./dbbackup:/dbbackup

  api:
    image: node
    env_file:
      - .env
    ports:
      - '$APP_PORT:$APP_PORT'
    volumes:
      - ./app:/home/node
    command: sh -c 'cd home/node; npm install;APP_PORT=$APP_PORT APP_HOST=$APP_HOST node ritmocardiacoserver.js'
    depends_on:
      - postgresdb